### ISSUE TITLE
Establish deployment from RMaaS static website

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/rmaas-api#54]
We own rmaas.io and records.digital.  Lets setup static web deployment (github pages?) for rmaas.io.  Maybe also redirection for records.digital to the same domain.

Separate task to "code-on-tapify" the actual RmaaS product.

**Comment by onthebreeze** [comment]
actually if github pages then we'll need a github org just for rmaas.  maybe it should just be an S3/CDN static web?  deployed from a new gs-gs rmaas-web repo or something?  Lets discuss.

**Comment by faizanvahevaria** [comment]
If you want to deploy on S3 then we need to build a deployment pipeline and don't need a separate GitHub Organization.


If we want to use ReDoc for API documentation, then we need a separate build+deploy pipeline.

**Comment by monkeypants** [comment]
:+1+ for static deployment in S3.

**Comment by roleyfoley** [comment]
If we are looking at deploying more of the rmass solution then having the static site in S3/codeontap would make sense since we need the pipeline for more complicated deployments anyway 

Does the site need any server functionality? contact us forms etc? 

What is the site built on? jekyll?

**Comment by monkeypants** [comment]
These questions are for you ^^^ @faizanvahevaria 

I think (but await Faizan's reply):

> Does the site need any server functionality? contact us forms etc?

Not yet, but it will have full RMaaS service...

> What is the site built on? jekyll?

Two parts; Jekyll + ReDoc

**Comment by faizanvahevaria** [comment]
> Does the site need any server functionality? contact us forms etc?

No, we don't need any extra back-end functionality. We can use free services like Formspree or Formingo to enable the contact form submission.
I guess we won't need contact form because this is an open source project.
Still, we can have a mailto link for contacting the developers.
If we need a complex support system then there are many ticket management services or GitHub Issues Tracking is good enough for Open Source.



> What is the site built on? jekyll?

Website is built on Jekyll and there is one part of it which should be built on ReDoc.
There is a possibility that Steve might want to switch to SwaggerUI.
Anyways, Jekyll cant' process ReDoc or SwaggerUI.
We need a build system like Gulp or anything else for building the website.
Currently, the website is hosted on GitHub Pages. It has it's own limitations.

We will need to use something else to build the website and publish the "_site" folder to S3 or other CDN on back to GitHub Pages(Only Static).

@roleyfoley 
@monkeypants

**Comment by roleyfoley** [comment]
Site is now being published through CodeOnTap to https://rmaas.io 
The site is based on the master branch of gs-gs/rmaas-web  and will push on every update

**Comment by roleyfoley** [comment]
@onthebreeze @monkeypants 
Whereabouts is the API Spec maintained for the the ReDoc site? redoc has a cli which should make it pretty easy to publish the spec to its own site to keep it up to date

**Comment by monkeypants** [comment]
@kshychko maybe you can answer this ^^^ ?

**Comment by roleyfoley** [comment]
Deployment established and working for the static site. Will create a new ticket for working with the API spec
